// Print all subsequences of a string
// Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

// Examples: 

// Input : abc
// Output : a, b, c, ab, bc, ac, abc

#include <iostream>
#include <unordered_set>
#include <string>
using namespace std;
unordered_set<string> s;
void printSubsequence(string inp)
{
    for (int i = 0; i < inp.length(); i++)
    {
        for (int j = inp.length(); j > i; j--)
        {
            string st = inp.substr(i, j);
            s.insert(st);

            for (int k = 1; k < st.length(); k++)
            {
                string sb = st;
                sb.erase(sb.begin() + k);
                printSubsequence(sb);
            }
        }
    }
    
}
void Subsequence(string input,string output){
    if (input.empty())
    {
        cout<<output<<endl;
        return;
    }
    Subsequence(input.substr(1),output+input[0]);
    Subsequence(input.substr(1),output);
    
}
int main()
{

    string input = "abc";
    Subsequence(input," ");
    printSubsequence(input);
    for (auto m : s)
    {
        cout << m << endl;
    }

    return 0;
}